version: '2'
services:
    web:
        image: lwenjim/nginx:test
        ports:
          - "80:80"
        volumes:
          - ./html:/usr/share/nginx/html
          - ./docker-compose-nginx.conf:/etc/nginx/nginx.conf
        networks:
            - code-network
        depends_on:
            - php
    php:
        image: lwenjim/php:test
        volumes:
          - ./html:/usr/share/nginx/html
        networks:
          - code-network
    golang:
        image: lwenjim/golang:test
        networks:
          - code-network
networks:
    code-network:
        driver: bridge