FROM php:8.2-fpm
WORKDIR /usr/share/nginx/html
ADD html /usr/share/nginx/html
RUN chmod -R 777 /usr/share/nginx/html/example-app/storage \
    && chmod 777 /usr/share/nginx/html/example-app/database/database.sqlite