version: '2'
services:
    web:
        image: nginx:latest
        ports:
          - "8000:80"
        volumes:
          - ./html:/usr/share/nginx/html
          - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
              - php
    php:
        image: php:7.0-fpm
        volumes:
          - ./html:/var/www/html
        networks:
          - code-network
networks:
    code-network:
        driver: bridge