apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      volumes:
        - name: html
          hostPath:
            path: /Users/jim/Workdata/nginx-limit-rate/html
            type: Directory
        - name: nginxconf
          hostPath:
            path: /Users/jim/Workdata/nginx-limit-rate/nginx.conf
            type: File
      containers:
        - name: nginx
          image: nginx:test
          volumeMounts:
            - mountPath: /data/nginx-bin/html
              name: html
            - mountPath: /data/nginx-bin/conf/nginx.conf
              name: nginxconf
          ports:
            - containerPort: 80
        - name: php
          image: php:fpm-alpine
          volumeMounts:
            - mountPath: /data/nginx-bin/html
              name: html
          ports:
            - containerPort: 9000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   type: NodePort
#   selector:
#     app: nginx
#   ports:
#     - protocol: TCP
#       port: 80
#       # targetPort: 80
#       nodePort: 30000
# ---
# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: my-ingress
# spec:
#   rules:
#     - host: "*.bar.com"
#       http:
#         paths:
#           - backend:
#               service:
#                 name: my-service
#                 port:
#                   number: 80
#             pathType: Prefix
#             path: "/abc"
