apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
          - name: html
            hostPath:
              path: ./html
              type: Directory  
          - name: nginx.conf
            hostPath:
              path: ./nginx.conf
              type: File
      containers:
        - name: nginx
          image: nginx:test
          volumnMounts:
          - mountPath: /data/nginx-bin/html
            name: html
          - mountPath: /data/nginx-bin/conf/nginx.conf
            name: nginx.conf
          ports:
            - containerPort: 80
        - name: php
          image: php:fpm-alpine
          volumnMounts:
          - mountPath: /data/nginx-bin/html
            name: html          
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007