apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: default
data:
  nginx.conf: |-
    worker_processes 1; 
    events {
        worker_connections 1024;
    }
    http {
        include mime.types;
        sendfile on;
        keepalive_timeout 65;
        limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;
        server {
            listen 80;
            server_name localhost;
            access_log /var/log/nginx/access.log combined;
            limit_req zone=one burst=20 nodelay;
            root /usr/share/nginx/html;
            location / {
                index index.html index.htm;
            }
            location ~ \.php$ {
                fastcgi_pass localhost:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                include fastcgi_params;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config-volumns
          configMap:
            defaultMode: 420
            name: nginx-configmap
      containers:
        - name: nginx
          image: lwenjim/nginx:test
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config-volumns
              subPath: nginx.conf
          ports:
            - containerPort: 80
        - name: php
          image: lwenjim/php:test
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: "a.bar.com"
      http:
        paths:
          - backend:
              service:
                name: nginx-service
                port:
                  number: 80
            pathType: Prefix
            path: "/"
